require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - "db/migrate/**/*"
    - "db/schema.rb"
    - "config/**/*"
    - "script/**/*"
    - "bin/{rails,rake,yarn}"
    - "vendor/bundle/**/*"

# Not require a top-level documentation of classes and modules
Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

# Too short methods lead to extraction of single-use methods, which can make
# the code easier to read (by naming things), but can also clutter the class
Metrics/MethodLength:
  Max: 20
  CountAsOne: ["array", "hash", "heredoc"]

# RSpec examples require many lines to Arrange, Act and Assert properly.
Metrics/BlockLength:
  CountAsOne: ["array", "hash", "heredoc"]
  Exclude:
    - "spec/**/*.rb"
    - "config/routes.rb"

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

RSpec/NestedGroups:
  Max: 5

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*'
    - 'spec/requests/**/*'

RSpec/ExampleLength:
  CountAsOne: ['array', 'hash', 'heredoc', 'method_call']

Style/HashEachMethods:
  Enabled: true

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/NegatedIf:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Lint/UnreachableLoop:
  AllowedPatterns:
    - '^maybe_.*'

Naming/VariableNumber:
  AllowedIdentifiers:
    - payee_num_2
    - payee_num_3