require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - "db/migrate/**/*"
    - "db/schema.rb"
    - "config/**/*"
    - "script/**/*"
    - "bin/{rails,rake,yarn}"
    - "vendor/"

# Not require a top-level documentation of classes and modules
Style/Documentation:
  Enabled: false

# Too short methods lead to extraction of single-use methods, which can make
# the code easier to read (by naming things), but can also clutter the class
Metrics/MethodLength:
  Max: 20
  CountAsOne: ["array", "hash", "heredoc"]

# RSpec examples require many lines to Arrange, Act and Assert properly.
Metrics/BlockLength:
  CountAsOne: ["array", "hash", "heredoc"]
  Exclude:
    - "spec/**/*.rb"
    - "config/routes.rb"

RSpec/NestedGroups:
  Max: 5

Style/HashEachMethods:
  Enabled: true

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/NegatedIf:
  Enabled: false
