name: Workflow for Ruby code coverage
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Ruby latest
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
      - name: Install dependencies
        run: bundle install
      - name: Run tests and collect coverage
        run: bundle exec rspec
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
